name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: 7.0
          mongodb-replica-set: rs0
          mongodb-port: 27017

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm test
